/**
 * Devcontainer config merge module for agent-env
 *
 * Implements build-time deep merge of agent-env managed properties
 * with repo-provided .devcontainer/devcontainer.json config.
 * See ADR-1 through ADR-7 in the tech spec for design rationale.
 */

import { parse as parseJsonc, type ParseError } from 'jsonc-parser';
import { constants } from 'node:fs';
import { access, lstat, readFile, readlink, rename, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join } from 'node:path';

import { CONTAINER_AGENT_ENV_DIR } from './container-env.js';
import { getBaselineConfigPath } from './devcontainer.js';
import { AGENT_ENV_DIR } from './types.js';

// ─── Types ───────────────────────────────────────────────────────────────────

/** Dependency injection interface for filesystem operations */
export interface DevcontainerMergeDeps {
  readFile: typeof readFile;
  writeFile: typeof writeFile;
  rename: typeof rename;
  access: typeof access;
  lstat?: typeof lstat;
  readlink?: typeof readlink;
}

const defaultMergeDeps: DevcontainerMergeDeps = {
  readFile,
  writeFile,
  rename,
  access,
  lstat,
  readlink,
};

/** Agent-env managed config properties injected during merge */
export interface ManagedConfig {
  /** Image URL (sourced from baseline config) */
  image: string;
  /** Instance name for name composition */
  instanceName: string;
  /** Container name for runArgs */
  containerName: string;
  /** initializeCommand string (sourced from baseline config) */
  initializeCmd: string;
  /** LABEL lifecycle command strings for composition */
  lifecycleCmds: Record<string, string>;
  /** Managed runArgs (e.g., ["--name=ae-repo-instance"]) */
  runArgs: string[];
  /** Managed containerEnv keys (always win in merge) */
  containerEnv: Record<string, string>;
  /** Managed mounts (empty by default — LABEL handles infrastructure mounts) */
  mounts: string[];
  /** Managed VS Code customizations */
  customizations: {
    vscode: {
      settings: Record<string, unknown>;
      extensions: string[];
    };
  };
}

/** Loose type for parsed JSONC repo config */
export type ParsedDevcontainerConfig = Record<string, unknown>;

/** Output type of mergeDevcontainerConfigs() and buildManagedOnly() */
export interface DevcontainerConfig {
  image: string;
  name: string;
  initializeCommand: string | Record<string, unknown>;
  runArgs: string[];
  containerEnv: Record<string, string>;
  mounts: string[];
  customizations: Record<string, unknown>;
  postCreateCommand?: unknown;
  postStartCommand?: unknown;
  postAttachCommand?: unknown;
  onCreateCommand?: unknown;
  updateContentCommand?: unknown;
  [key: string]: unknown;
}

// ─── Constants ───────────────────────────────────────────────────────────────

/** Status bar JSON filename */
const STATUS_BAR_JSON_FILENAME = 'statusBar.json';

/**
 * LABEL lifecycle command strings that must match the Dockerfile LABEL
 * devcontainer.metadata values.
 * SYNC: image/Dockerfile lines 275-276
 */
export const LABEL_LIFECYCLE_CMDS: Record<string, string> = {
  postCreateCommand: '/usr/local/bin/post-create.sh',
  postStartCommand:
    'sudo /usr/local/bin/fix-ssh-socket-permissions.sh; sudo /usr/local/bin/start-sshd.sh; /home/node/.local/bin/tmux-session --detached || true; : > /tmp/install-shared-skills.log; /usr/local/bin/install-shared-skills.sh >> /tmp/install-shared-skills.log 2>&1 || true',
};

/** Lifecycle command names handled by composeAllLifecycle (NOT initializeCommand, NOT waitFor) */
const COMPOSABLE_LIFECYCLE_CMDS = [
  'postCreateCommand',
  'postStartCommand',
  'postAttachCommand',
  'onCreateCommand',
  'updateContentCommand',
] as const;

/** Auto-generated file header prefix */
const AUTO_GENERATED_HEADER = '// AUTO-GENERATED by agent-env';

// ─── Repo Config Discovery ──────────────────────────────────────────────────

/**
 * Search for and read a repo's devcontainer config file.
 *
 * Checks three locations:
 *   1. .devcontainer/devcontainer.json
 *   2. devcontainer.json (root)
 *   3. .devcontainer.json (root)
 *
 * Returns the parsed config or undefined if none found.
 * Throws on parse errors (invalid JSONC) — does NOT silently return undefined.
 */
export async function readRepoConfig(
  workspacePath: string,
  deps: Pick<DevcontainerMergeDeps, 'readFile' | 'access'> &
    Partial<Pick<DevcontainerMergeDeps, 'lstat' | 'readlink'>> = defaultMergeDeps,
  logger?: { warn: (msg: string) => void }
): Promise<ParsedDevcontainerConfig | undefined> {
  const candidates = [
    join(workspacePath, '.devcontainer', 'devcontainer.json'),
    join(workspacePath, 'devcontainer.json'),
    join(workspacePath, '.devcontainer.json'),
  ];

  for (const candidate of candidates) {
    // Defense-in-depth: skip symlinks pointing into .agent-env/ (ephemeral symlinks
    // created by `agent-env code` should be cleaned up, but guard against stale ones)
    if (deps.lstat && deps.readlink) {
      try {
        const linkStat = await deps.lstat(candidate);
        if (linkStat.isSymbolicLink()) {
          const target = await deps.readlink(candidate);
          if (target.includes(AGENT_ENV_DIR)) {
            logger?.warn(
              `Skipping symlink to agent-env config at ${candidate} — not a repo config`
            );
            continue;
          }
        }
      } catch {
        // lstat failed (ENOENT etc.) — fall through to normal access/read path
      }
    }

    let content: string;
    try {
      await deps.access(candidate, constants.F_OK);
      content = await deps.readFile(candidate, 'utf-8');
    } catch (err) {
      const code = (err as NodeJS.ErrnoException | undefined)?.code;
      if (code === 'ENOENT') {
        continue;
      }
      throw err;
    }

    // Feedback loop guard: skip auto-generated configs
    if (content.startsWith(AUTO_GENERATED_HEADER)) {
      logger?.warn(
        `Skipping auto-generated config at ${candidate} — this appears to be agent-env's own output, not a repo config`
      );
      continue;
    }

    // Parse JSONC
    const errors: ParseError[] = [];
    const parsed = parseJsonc(content, errors, { allowTrailingComma: true });

    if (errors.length > 0) {
      throw new Error(`Failed to parse devcontainer config at ${candidate}: Invalid JSONC`);
    }

    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      throw new Error(
        `Failed to parse devcontainer config at ${candidate}: Expected a JSON object`
      );
    }

    return parsed as ParsedDevcontainerConfig;
  }

  return undefined;
}

// ─── Validation ──────────────────────────────────────────────────────────────

/**
 * Validate a repo config for compatibility with agent-env.
 *
 * Rejects configs with build/compose properties.
 * Warns when repo specifies a different image than the managed image.
 */
export function validateRepoConfig(
  config: ParsedDevcontainerConfig,
  managedImage: string,
  logger?: { warn: (msg: string) => void }
): void {
  const rejectedProps = ['build', 'dockerFile', 'dockerfile', 'dockerComposeFile'];

  for (const prop of rejectedProps) {
    if (prop in config && config[prop] !== undefined) {
      throw new Error(
        `agent-env requires the managed image. Remove '${prop}' from .devcontainer/devcontainer.json to use agent-env.`
      );
    }
  }

  if ('image' in config && config.image !== undefined) {
    const repoImage = String(config.image);
    if (repoImage !== managedImage) {
      logger?.warn(
        `Repo config specifies image '${repoImage}' which will be overridden by agent-env managed image.`
      );
    }
  }
}

// ─── Name Composition (ADR-3) ────────────────────────────────────────────────

/**
 * Compose the devcontainer name from instance name and optional repo name.
 *
 * If repo provides a name → use as base, append " - {instanceName}"
 * If no repo name → use instanceName alone
 */
export function composeName(instanceName: string, repoName?: unknown): string {
  if (typeof repoName === 'string' && repoName.trim()) {
    return `${repoName} - ${instanceName}`;
  }
  return instanceName;
}

// ─── Lifecycle Composition (ADR-4) ───────────────────────────────────────────

/**
 * Compose a single lifecycle command from managed and repo values.
 *
 * If repo has no command → return managed as plain string.
 * If repo has a string/array → wrap as "repo" key alongside managed "agent-env" key.
 * If repo has an object → merge keys (agent-env reserves "agent-env" key).
 */
export function composeLifecycle(
  managedCmd: string,
  repoCmd?: unknown
): string | Record<string, unknown> {
  if (repoCmd === undefined || repoCmd === null) {
    return managedCmd;
  }

  if (typeof repoCmd === 'string') {
    return { 'agent-env': managedCmd, repo: repoCmd };
  }

  if (Array.isArray(repoCmd)) {
    return { 'agent-env': managedCmd, repo: repoCmd };
  }

  if (typeof repoCmd === 'object') {
    return { 'agent-env': managedCmd, ...(repoCmd as Record<string, unknown>) };
  }

  // Unexpected type (number, boolean, etc.) — treat as absent
  return managedCmd;
}

/**
 * Compose all non-initializeCommand lifecycle commands.
 *
 * For commands with a LABEL value (postCreateCommand, postStartCommand),
 * the managed key references the LABEL's command string.
 * For commands with no LABEL value, only wraps if repo defines one.
 * Omits properties where neither managed nor repo defines a value.
 */
export function composeAllLifecycle(
  managedLifecycleCmds: Record<string, string>,
  repoLifecycleCmds: Record<string, unknown>
): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const cmdName of COMPOSABLE_LIFECYCLE_CMDS) {
    const managedCmd = managedLifecycleCmds[cmdName];
    const repoCmd = repoLifecycleCmds[cmdName];

    if (managedCmd && repoCmd !== undefined && repoCmd !== null) {
      // Both managed (LABEL) and repo define this command — compose
      result[cmdName] = composeLifecycle(managedCmd, repoCmd);
    } else if (managedCmd && (repoCmd === undefined || repoCmd === null)) {
      // Only LABEL defines it — but since LABEL handles it natively,
      // we DON'T emit it in the config (config would override LABEL's scalar form)
      // However, the destructuring already removed it from repoRest,
      // so we need to NOT emit it here to let LABEL handle it.
      // Skip — let LABEL handle it natively
    } else if (!managedCmd && repoCmd !== undefined && repoCmd !== null) {
      // Only repo defines it — wrap with just the repo key
      if (typeof repoCmd === 'string') {
        result[cmdName] = { repo: repoCmd };
      } else if (Array.isArray(repoCmd)) {
        result[cmdName] = { repo: repoCmd };
      } else if (typeof repoCmd === 'object') {
        result[cmdName] = repoCmd;
      }
    }
    // Neither defines it — omit
  }

  return result;
}

// ─── RunArgs Merge ───────────────────────────────────────────────────────────

/**
 * Flag-aware merge of runArgs arrays.
 *
 * Strips `--name=value` (single element) and `--name value` (two consecutive
 * elements) from repo args before concatenating with managed args.
 * Uses exact string operations, not regex.
 */
export function mergeRunArgs(managedArgs: string[], repoArgs?: unknown): string[] {
  if (!Array.isArray(repoArgs)) {
    return [...managedArgs];
  }

  const filtered: string[] = [];
  let i = 0;
  while (i < repoArgs.length) {
    const arg = String(repoArgs[i]);

    // Strip --name=value form
    if (arg.startsWith('--name=')) {
      i++;
      continue;
    }

    // Strip --name value form (exact match, NOT prefix match)
    if (arg === '--name') {
      // Skip --name and the next element (the value), if present
      i += i + 1 < repoArgs.length ? 2 : 1;
      continue;
    }

    filtered.push(arg);
    i++;
  }

  return [...managedArgs, ...filtered];
}

// ─── Mounts Merge ────────────────────────────────────────────────────────────

/**
 * Extract the target path from a mount specification.
 * Handles both string-form and object-form mounts.
 */
function extractMountTarget(mount: unknown): string | undefined {
  if (typeof mount === 'string') {
    // Parse "source=...,target=...,type=..." form
    const parts = mount.split(',');
    for (const part of parts) {
      const trimmed = part.trim();
      if (trimmed.startsWith('target=') || trimmed.startsWith('destination=')) {
        return trimmed.split('=').slice(1).join('=');
      }
    }
    return undefined;
  }

  if (typeof mount === 'object' && mount !== null) {
    const obj = mount as Record<string, unknown>;
    if (typeof obj.target === 'string') return obj.target;
    if (typeof obj.destination === 'string') return obj.destination;
  }

  return undefined;
}

/**
 * Merge mount arrays with target-path deduplication.
 * Managed mounts win on target path collision.
 */
export function mergeMounts(managedMounts: string[], repoMounts?: unknown): string[] {
  if (!Array.isArray(repoMounts)) {
    return [...managedMounts];
  }

  // Build set of managed mount targets
  const managedTargets = new Set<string>();
  for (const mount of managedMounts) {
    const target = extractMountTarget(mount);
    if (target) managedTargets.add(target);
  }

  // Filter repo mounts: drop any that target a managed path
  const filteredRepo: string[] = [];
  for (const mount of repoMounts) {
    const target = extractMountTarget(mount);
    if (target && managedTargets.has(target)) {
      continue; // managed wins
    }
    // Convert object-form mounts to string for consistency
    if (typeof mount === 'string') {
      filteredRepo.push(mount);
    } else if (typeof mount === 'object' && mount !== null) {
      // Object-form mounts: convert to string form
      const obj = mount as Record<string, unknown>;
      const parts: string[] = [];
      if (obj.source) parts.push(`source=${obj.source}`);
      if (obj.target) parts.push(`target=${obj.target}`);
      else if (obj.destination) parts.push(`target=${obj.destination}`);
      if (obj.type) parts.push(`type=${obj.type}`);
      filteredRepo.push(parts.join(','));
    }
  }

  return [...managedMounts, ...filteredRepo];
}

// ─── Customizations Merge ────────────────────────────────────────────────────

/**
 * Deep merge VS Code customizations.
 *
 * Extensions: concatenate + deduplicate (case-insensitive).
 * Settings: object merge (managed wins for managed keys).
 * Filewatcher commands: append managed watcher, deduplicate by match field.
 */
export function deepMergeCustomizations(
  managed: ManagedConfig['customizations'],
  repo?: unknown
): Record<string, unknown> {
  if (!repo || typeof repo !== 'object') {
    return {
      vscode: {
        settings: { ...managed.vscode.settings },
        extensions: [...managed.vscode.extensions],
      },
    };
  }

  const repoCustom = repo as Record<string, unknown>;
  const repoVscode =
    typeof repoCustom.vscode === 'object' && repoCustom.vscode !== null
      ? (repoCustom.vscode as Record<string, unknown>)
      : {};

  // Merge extensions: concat + dedupe (case-insensitive)
  const repoExtensions = Array.isArray(repoVscode.extensions)
    ? (repoVscode.extensions as string[])
    : [];
  const allExtensions = [...managed.vscode.extensions, ...repoExtensions];
  const seen = new Set<string>();
  const dedupedExtensions: string[] = [];
  for (const ext of allExtensions) {
    const lower = ext.toLowerCase();
    if (!seen.has(lower)) {
      seen.add(lower);
      dedupedExtensions.push(ext);
    }
  }

  // Merge settings: repo settings first, then managed overlays
  const repoSettings =
    typeof repoVscode.settings === 'object' && repoVscode.settings !== null
      ? (repoVscode.settings as Record<string, unknown>)
      : {};

  // Special handling for filewatcher.commands: merge arrays, deduplicate by match
  const repoFilewatcherCommands = Array.isArray(repoSettings['filewatcher.commands'])
    ? (repoSettings['filewatcher.commands'] as unknown[])
    : [];
  const managedFilewatcherCommands = Array.isArray(managed.vscode.settings['filewatcher.commands'])
    ? (managed.vscode.settings['filewatcher.commands'] as unknown[])
    : [];

  const mergedFilewatcherCommands = [...repoFilewatcherCommands];
  for (const managedCmd of managedFilewatcherCommands) {
    if (typeof managedCmd !== 'object' || managedCmd === null) continue;
    const mCmd = managedCmd as { match?: unknown };
    const alreadyExists = mergedFilewatcherCommands.some((existing) => {
      if (typeof existing !== 'object' || existing === null) return false;
      return (existing as { match?: unknown }).match === mCmd.match;
    });
    if (!alreadyExists) {
      mergedFilewatcherCommands.push(managedCmd);
    }
  }

  const mergedSettings: Record<string, unknown> = {
    ...repoSettings,
    ...managed.vscode.settings,
  };
  // Override filewatcher.commands with merged version
  if (mergedFilewatcherCommands.length > 0) {
    mergedSettings['filewatcher.commands'] = mergedFilewatcherCommands;
  }

  // Merge non-vscode customizations (pass-through)
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(repoCustom)) {
    if (key !== 'vscode') {
      result[key] = value;
    }
  }

  result.vscode = {
    ...repoVscode,
    settings: mergedSettings,
    extensions: dedupedExtensions,
  };

  return result;
}

// ─── Main Merge Function (ADR-7) ────────────────────────────────────────────

/**
 * Build a DevcontainerConfig from managed defaults alone (no repo config).
 *
 * Emits initializeCommand as plain string (no object form needed).
 * OMITS postCreateCommand and postStartCommand — these are Layer 1 (LABEL)
 * and the LABEL handles them natively when no config file overrides them.
 */
export function buildManagedOnly(managed: ManagedConfig): DevcontainerConfig {
  return {
    image: managed.image,
    name: managed.instanceName,
    initializeCommand: managed.initializeCmd,
    runArgs: [...managed.runArgs],
    containerEnv: { ...managed.containerEnv },
    mounts: [...managed.mounts],
    customizations: deepMergeCustomizations(managed.customizations),
  };
}

/**
 * Deep merge agent-env managed properties with a repo's devcontainer config.
 *
 * Unknown/new devcontainer properties pass through via ...repoRest spread.
 * Managed-owned keys are set after spread, so they always win.
 */
export function mergeDevcontainerConfigs(
  managed: ManagedConfig,
  repoConfig?: ParsedDevcontainerConfig
): DevcontainerConfig {
  if (!repoConfig) return buildManagedOnly(managed);

  const {
    name,
    image: _image,
    initializeCommand,
    postCreateCommand,
    postStartCommand,
    postAttachCommand,
    onCreateCommand,
    updateContentCommand,
    runArgs,
    containerEnv,
    customizations,
    mounts,
    ...repoRest
  } = repoConfig;

  return {
    ...repoRest,
    image: managed.image,
    name: composeName(managed.instanceName, name),
    initializeCommand: composeLifecycle(managed.initializeCmd, initializeCommand),
    ...composeAllLifecycle(managed.lifecycleCmds, {
      postCreateCommand,
      postStartCommand,
      postAttachCommand,
      onCreateCommand,
      updateContentCommand,
    }),
    runArgs: mergeRunArgs(managed.runArgs, runArgs),
    containerEnv: {
      ...(typeof containerEnv === 'object' && containerEnv !== null
        ? Object.fromEntries(
            Object.entries(containerEnv as Record<string, unknown>).map(([k, v]) => [k, String(v)])
          )
        : {}),
      ...managed.containerEnv,
    },
    mounts: mergeMounts(managed.mounts, mounts),
    customizations: deepMergeCustomizations(managed.customizations, customizations),
  } as DevcontainerConfig;
}

// ─── Managed Defaults ────────────────────────────────────────────────────────

/**
 * Load managed default values from the baseline config file.
 *
 * Selectively extracts: image, initializeCommand, and AGENT_ENV_CONTAINER from containerEnv.
 * Does NOT extract mounts (LABEL handles those).
 */
export async function loadManagedDefaults(
  deps: Pick<DevcontainerMergeDeps, 'readFile'> = defaultMergeDeps
): Promise<{ image: string; initializeCmd: string; baseContainerEnv: Record<string, string> }> {
  const baselinePath = getBaselineConfigPath();
  const configPath = join(baselinePath, 'devcontainer.json');

  let content: string;
  try {
    content = await deps.readFile(configPath, 'utf-8');
  } catch {
    throw new Error(
      `Failed to load managed defaults from baseline config: ${configPath}. Ensure agent-env package is intact.`
    );
  }

  // Parse JSONC
  const errors: ParseError[] = [];
  const config = parseJsonc(content, errors, { allowTrailingComma: true }) as Record<
    string,
    unknown
  >;

  if (errors.length > 0) {
    throw new Error(
      `Failed to load managed defaults from baseline config: ${configPath}. Ensure agent-env package is intact.`
    );
  }

  if (typeof config.image !== 'string') {
    throw new Error(
      `Failed to load managed defaults from baseline config: ${configPath}. Missing 'image' field.`
    );
  }

  if (typeof config.initializeCommand !== 'string') {
    throw new Error(
      `Failed to load managed defaults from baseline config: ${configPath}. Missing 'initializeCommand' field.`
    );
  }

  // Extract only AGENT_ENV_CONTAINER from containerEnv (defensive duplication from LABEL)
  const baseContainerEnv: Record<string, string> = {};
  if (typeof config.containerEnv === 'object' && config.containerEnv !== null) {
    const env = config.containerEnv as Record<string, unknown>;
    if (typeof env.AGENT_ENV_CONTAINER === 'string') {
      baseContainerEnv.AGENT_ENV_CONTAINER = env.AGENT_ENV_CONTAINER;
    }
  }

  return {
    image: config.image,
    initializeCmd: config.initializeCommand,
    baseContainerEnv,
  };
}

// ─── Generated Config I/O ────────────────────────────────────────────────────

/**
 * Get the agent-env package version for the generated config header.
 */
function getPackageVersion(): string {
  try {
    const req = createRequire(import.meta.url);
    const pkg = req('../../package.json') as { version: string };
    return pkg.version;
  } catch {
    return 'unknown';
  }
}

/**
 * Write a generated devcontainer config with auto-generated header comment.
 *
 * Uses atomic write pattern (tmp + rename) to prevent corruption.
 */
export async function writeGeneratedConfig(
  outputPath: string,
  config: DevcontainerConfig,
  deps: Pick<DevcontainerMergeDeps, 'writeFile' | 'rename'> = defaultMergeDeps
): Promise<void> {
  const version = getPackageVersion();
  const header = `${AUTO_GENERATED_HEADER} v${version}. Do not edit.\n`;
  const json = JSON.stringify(config, null, 2);
  const content = `${header}${json}\n`;

  const tmpPath = `${outputPath}.tmp`;
  await deps.writeFile(tmpPath, content, 'utf-8');
  await deps.rename(tmpPath, outputPath);
}

// ─── SSH Agent Forwarding ────────────────────────────────────────────────────

/**
 * Container-side path where the forwarded SSH agent socket is exposed.
 *
 * This is kept constant across platforms so everything downstream (the
 * SSH_AUTH_SOCK env var, fix-ssh-socket-permissions.sh, sshd) can rely on a
 * single path regardless of where the host socket actually lives.
 */
export const SSH_AGENT_CONTAINER_SOCKET = '/run/host-services/ssh-auth.sock';

/** A bind mount + matching SSH_AUTH_SOCK env for forwarding the host SSH agent. */
export interface SshAgentForwarding {
  mount: string;
  env: Record<string, string>;
}

/**
 * Resolve the host SSH agent socket mount for the current platform.
 *
 * The correct host source differs by platform and therefore cannot live in the
 * image's static devcontainer.metadata LABEL:
 *
 * - macOS (Docker Desktop / OrbStack): the runtime injects the host agent at a
 *   fixed path inside its VM, `/run/host-services/ssh-auth.sock`. That literal
 *   path must be used as the mount source — it is special-cased by the runtime
 *   and is not a normal file on the macOS host.
 * - Linux (native Docker / Podman): there is no magic path; the host's real
 *   `$SSH_AUTH_SOCK` must be forwarded directly. The mount source is emitted
 *   as the devcontainer variable `${localEnv:SSH_AUTH_SOCK}` rather than the
 *   concrete path: agent sockets under `/tmp/ssh-*` or `/run/user/...` are
 *   ephemeral and change across logout/reboot, and the generated config is
 *   reused by attach/code to restart containers without being regenerated.
 *   The variable defers resolution to each `devcontainer up`, so a restart
 *   picks up the current shell's agent instead of a stale baked-in path.
 *
 * Returns `null` when no agent is available to forward (Linux with no
 * `SSH_AUTH_SOCK`), so callers can omit the mount entirely rather than emit a
 * bind mount with a non-existent source — which makes `docker run` fail hard.
 * The `sshAuthSock` value only gates this decision; it is never persisted.
 *
 * @param platform - Host platform (defaults to `process.platform`)
 * @param sshAuthSock - Host SSH agent socket path (defaults to `process.env.SSH_AUTH_SOCK`)
 */
export function resolveSshAgentMount(
  platform: NodeJS.Platform = process.platform,
  sshAuthSock: string | undefined = process.env.SSH_AUTH_SOCK
): SshAgentForwarding | null {
  const target = SSH_AGENT_CONTAINER_SOCKET;
  const forwarding = (source: string): SshAgentForwarding => ({
    mount: `source=${source},target=${target},type=bind`,
    env: { SSH_AUTH_SOCK: target },
  });

  if (platform === 'darwin') {
    return forwarding(target);
  }

  if (sshAuthSock && sshAuthSock.length > 0) {
    // Literal devcontainer variable (not a JS template) — substituted by the
    // devcontainer CLI at each `up`, so the persisted config never holds an
    // ephemeral socket path.
    return forwarding('${localEnv:SSH_AUTH_SOCK}');
  }

  return null;
}

// ─── ManagedConfig Builder ───────────────────────────────────────────────────

/**
 * Build a ManagedConfig from instance parameters and managed defaults.
 *
 * Callers provide instance-specific fields; this function assembles
 * the full ManagedConfig with VS Code settings and lifecycle commands.
 */
export function buildManagedConfig(
  defaults: { image: string; initializeCmd: string; baseContainerEnv: Record<string, string> },
  params: {
    instanceName: string;
    containerName: string;
    repoSlug: string;
    purpose: string;
    /**
     * Platform-resolved SSH agent forwarding (see resolveSshAgentMount). When
     * omitted, the caller defaults to the current platform. Pass `null`
     * explicitly to disable SSH agent forwarding.
     */
    sshAgent?: SshAgentForwarding | null;
  }
): ManagedConfig {
  const statusBarWatcher = {
    match: `${STATUS_BAR_JSON_FILENAME}$`,
    event: 'onFolderChange',
    vscodeTask: 'betterStatusBar.refreshButtons',
  };

  const sshAgent = params.sshAgent === undefined ? resolveSshAgentMount() : params.sshAgent;

  return {
    image: defaults.image,
    instanceName: params.instanceName,
    containerName: params.containerName,
    initializeCmd: defaults.initializeCmd,
    lifecycleCmds: { ...LABEL_LIFECYCLE_CMDS },
    runArgs: [`--name=${params.containerName}`],
    containerEnv: {
      ...defaults.baseContainerEnv,
      AGENT_ENV_INSTANCE: params.instanceName,
      AGENT_ENV_REPO: params.repoSlug,
      AGENT_ENV_PURPOSE: params.purpose,
      ...(sshAgent?.env ?? {}),
    },
    mounts: sshAgent ? [sshAgent.mount] : [],
    customizations: {
      vscode: {
        settings: {
          'betterStatusBar.configurationFile': `${CONTAINER_AGENT_ENV_DIR}/${STATUS_BAR_JSON_FILENAME}`,
          'filewatcher.commands': [statusBarWatcher],
        },
        extensions: [],
      },
    },
  };
}
