#!/bin/bash
# start-sshd.sh - Start SSH daemon if host keys are present
#
# Called from postStartCommand (runs on every container start).
# Host keys are generated by post-create.sh (runs once after creation).
#
# Must run as root (via sudo). Safe to call repeatedly — skips if already running.

set -euo pipefail

if [ "$EUID" -ne 0 ]; then
  echo "  ⚠ start-sshd.sh must run as root (use sudo)" >&2
  exit 1
fi

if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
  echo "  SSH: Host keys not found — skipping sshd start"
  echo "  SSH: Run post-create.sh first to generate keys"
  exit 0
fi

if pgrep -x sshd >/dev/null 2>&1; then
  echo "  SSH: sshd already running"
  exit 0
fi

if /usr/sbin/sshd; then
  echo "  ✓ SSH server started"
else
  echo "  ⚠ SSH server failed to start" >&2
  exit 1
fi
